import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const skModernistBold = localFont({
  src: "./fonts/Sk-Modernist-Bold.woff",
  variable: "--font-modernist-bold",
  weight: "100 900",
});
const skModernistRegular = localFont({
  src: "./fonts/Sk-Modernist-Regular.woff",
  variable: "--font-modernist-reg",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${skModernistBold.variable} ${skModernistRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
